#!/bin/bash
# OpenAlgo Docker Startup Script
# Optimized for Coolify/Dokploy deployment with proper .env handling

set -e

echo "[OpenAlgo] Starting up..."

# Configuration
ENV_FILE="/app/.env"
APP_PORT="${PORT:-5000}"

# Extract domain from HOST_SERVER for WebSocket URL
if [ -n "$HOST_SERVER" ]; then
    HOST_DOMAIN="${HOST_SERVER#https://}"
    HOST_DOMAIN="${HOST_DOMAIN#http://}"
fi

# Function to generate .env file with proper quoting
generate_env_file() {
    echo "[OpenAlgo] Generating .env file from environment variables..."
    
    cat > "$ENV_FILE" << 'ENVEOF'
# OpenAlgo Environment Configuration
# Auto-generated by Docker entrypoint
ENVEOF

    # Core configuration - using proper quoting for all values
    cat >> "$ENV_FILE" << EOF
ENV_CONFIG_VERSION='1.0.4'

# Broker Configuration
BROKER_API_KEY='${BROKER_API_KEY:-}'
BROKER_API_SECRET='${BROKER_API_SECRET:-}'
BROKER_API_KEY_MARKET='${BROKER_API_KEY_MARKET:-}'
BROKER_API_SECRET_MARKET='${BROKER_API_SECRET_MARKET:-}'

# URLs
REDIRECT_URL='${REDIRECT_URL:-}'
HOST_SERVER='${HOST_SERVER:-}'

# Valid Brokers
VALID_BROKERS='${VALID_BROKERS:-fivepaisa,fivepaisaxts,aliceblue,angel,compositedge,dhan,dhan_sandbox,definedge,firstock,flattrade,fyers,groww,ibulls,iifl,indmoney,jainamxts,kotak,motilal,mstock,paytm,pocketful,samco,shoonya,tradejini,upstox,wisdom,zebu,zerodha}'

# Security
APP_KEY='${APP_KEY:-}'
API_KEY_PEPPER='${API_KEY_PEPPER:-}'

# Database
DATABASE_URL='${DATABASE_URL:-sqlite:///db/openalgo.db}'
LATENCY_DATABASE_URL='${LATENCY_DATABASE_URL:-sqlite:///db/latency.db}'
LOGS_DATABASE_URL='${LOGS_DATABASE_URL:-sqlite:///db/logs.db}'
SANDBOX_DATABASE_URL='${SANDBOX_DATABASE_URL:-sqlite:///db/sandbox.db}'

# Server Configuration
NGROK_ALLOW='FALSE'
FLASK_HOST_IP='0.0.0.0'
FLASK_PORT='${APP_PORT}'
FLASK_DEBUG='${FLASK_DEBUG:-0}'
FLASK_ENV='${FLASK_ENV:-production}'

# WebSocket
WEBSOCKET_HOST='0.0.0.0'
WEBSOCKET_PORT='${WEBSOCKET_PORT:-8765}'
EOF

    # Add WebSocket URL with proper domain substitution
    if [ -n "$WEBSOCKET_URL" ]; then
        echo "WEBSOCKET_URL='${WEBSOCKET_URL}'" >> "$ENV_FILE"
    elif [ -n "$HOST_DOMAIN" ]; then
        echo "WEBSOCKET_URL='wss://${HOST_DOMAIN}/ws'" >> "$ENV_FILE"
    else
        echo "WEBSOCKET_URL=''" >> "$ENV_FILE"
    fi

    cat >> "$ENV_FILE" << EOF

# ZeroMQ
ZMQ_HOST='0.0.0.0'
ZMQ_PORT='${ZMQ_PORT:-5555}'

# Logging
LOG_TO_FILE='${LOG_TO_FILE:-True}'
LOG_LEVEL='${LOG_LEVEL:-INFO}'
LOG_DIR='${LOG_DIR:-log}'
LOG_FORMAT='[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
LOG_RETENTION='${LOG_RETENTION:-14}'
LOG_COLORS='True'
FORCE_COLOR='1'

# Rate Limits
LOGIN_RATE_LIMIT_MIN='${LOGIN_RATE_LIMIT_MIN:-5 per minute}'
LOGIN_RATE_LIMIT_HOUR='${LOGIN_RATE_LIMIT_HOUR:-25 per hour}'
RESET_RATE_LIMIT='${RESET_RATE_LIMIT:-15 per hour}'
API_RATE_LIMIT='${API_RATE_LIMIT:-50 per second}'
ORDER_RATE_LIMIT='${ORDER_RATE_LIMIT:-10 per second}'
SMART_ORDER_RATE_LIMIT='${SMART_ORDER_RATE_LIMIT:-2 per second}'
WEBHOOK_RATE_LIMIT='${WEBHOOK_RATE_LIMIT:-100 per minute}'
STRATEGY_RATE_LIMIT='${STRATEGY_RATE_LIMIT:-200 per minute}'

# API Settings
SMART_ORDER_DELAY='${SMART_ORDER_DELAY:-0.5}'
SESSION_EXPIRY_TIME='${SESSION_EXPIRY_TIME:-03:00}'

# CORS Configuration
CORS_ENABLED='${CORS_ENABLED:-TRUE}'
CORS_ALLOWED_ORIGINS='${CORS_ALLOWED_ORIGINS:-${HOST_SERVER}}'
CORS_ALLOWED_METHODS='${CORS_ALLOWED_METHODS:-GET,POST,DELETE,PUT,PATCH}'
CORS_ALLOWED_HEADERS='${CORS_ALLOWED_HEADERS:-Content-Type,Authorization,X-Requested-With}'
CORS_EXPOSED_HEADERS='${CORS_EXPOSED_HEADERS:-}'
CORS_ALLOW_CREDENTIALS='${CORS_ALLOW_CREDENTIALS:-FALSE}'
CORS_MAX_AGE='${CORS_MAX_AGE:-86400}'

# CSP Configuration - properly quoted for python-dotenv
CSP_ENABLED='${CSP_ENABLED:-TRUE}'
CSP_REPORT_ONLY='${CSP_REPORT_ONLY:-FALSE}'
EOF

    # CSP values need special handling - use double quotes to wrap single-quoted CSP keywords
    cat >> "$ENV_FILE" << 'CSPEOF'
CSP_DEFAULT_SRC="'self'"
CSP_SCRIPT_SRC="'self' 'unsafe-inline' https://cdn.socket.io https://static.cloudflareinsights.com"
CSP_STYLE_SRC="'self' 'unsafe-inline'"
CSP_IMG_SRC="'self' data:"
CSPEOF

    # CSP_CONNECT_SRC needs domain substitution
    if [ -n "$HOST_DOMAIN" ]; then
        echo "CSP_CONNECT_SRC=\"'self' wss://${HOST_DOMAIN} wss: ws: https://cdn.socket.io\"" >> "$ENV_FILE"
    else
        echo "CSP_CONNECT_SRC=\"'self' wss: ws: https://cdn.socket.io\"" >> "$ENV_FILE"
    fi

    cat >> "$ENV_FILE" << 'CSPEOF2'
CSP_FONT_SRC="'self'"
CSP_OBJECT_SRC="'none'"
CSP_MEDIA_SRC="'self' data: https://*.amazonaws.com https://*.cloudfront.net"
CSP_FRAME_SRC="'self'"
CSP_FORM_ACTION="'self'"
CSP_FRAME_ANCESTORS="'self'"
CSP_BASE_URI="'self'"
CSP_UPGRADE_INSECURE_REQUESTS='TRUE'
CSP_REPORT_URI=''

# CSRF Configuration
CSRF_ENABLED='TRUE'
CSRF_TIME_LIMIT=''

# Cookie Configuration
SESSION_COOKIE_NAME='session'
CSRF_COOKIE_NAME='csrf_token'
CSPEOF2

    echo "[OpenAlgo] .env file generated successfully"
}

# Check if we need to generate .env
if [ ! -s "$ENV_FILE" ]; then
    if [ -n "$HOST_SERVER" ]; then
        generate_env_file
    else
        echo "============================================"
        echo "Error: No .env file and HOST_SERVER not set"
        echo ""
        echo "For cloud deployment, set these environment variables:"
        echo "  - HOST_SERVER (e.g., https://your-app.example.com)"
        echo "  - REDIRECT_URL"
        echo "  - BROKER_API_KEY"
        echo "  - BROKER_API_SECRET"
        echo "  - APP_KEY (python -c \"import secrets; print(secrets.token_hex(32))\")"
        echo "  - API_KEY_PEPPER (generate another one)"
        echo "============================================"
        exit 1
    fi
else
    echo "[OpenAlgo] Using existing .env file"
fi

# Create required directories
for dir in db log log/strategies strategies strategies/scripts keys; do
    mkdir -p "$dir" 2>/dev/null || true
done

# Set permissions if possible
if [ -w "." ]; then
    chmod -R 755 db log strategies 2>/dev/null || true
    chmod 700 keys 2>/dev/null || true
fi

cd /app

# Start WebSocket proxy server
echo "[OpenAlgo] Starting WebSocket proxy server on port 8765..."
/app/.venv/bin/python -m websocket_proxy.server &
WEBSOCKET_PID=$!
echo "[OpenAlgo] WebSocket proxy server started with PID $WEBSOCKET_PID"

# Signal handler for graceful shutdown
cleanup() {
    echo "[OpenAlgo] Shutting down..."
    [ -n "$WEBSOCKET_PID" ] && kill $WEBSOCKET_PID 2>/dev/null
    exit 0
}
trap cleanup SIGTERM SIGINT

# Start the application
echo "[OpenAlgo] Starting application on port ${APP_PORT} with eventlet..."
exec /app/.venv/bin/gunicorn \
    --worker-class eventlet \
    --workers 1 \
    --bind 0.0.0.0:${APP_PORT} \
    --timeout 120 \
    --graceful-timeout 30 \
    --log-level warning \
    app:app
