#!/bin/bash
# =============================================================================
# OpenAlgo Docker Startup Script
# Optimized for Coolify, Dokploy, Railway, Docker Compose & Standalone deployments
# =============================================================================

set -e

echo "[OpenAlgo] Starting up..."

# Determine writable .env location
ENV_FILE="/app/.env"
APP_PORT="${PORT:-5000}"

# Extract domain from HOST_SERVER for WebSocket URL if provided
if [ -n "$HOST_SERVER" ]; then
    HOST_DOMAIN="${HOST_SERVER#https://}"
    HOST_DOMAIN="${HOST_DOMAIN#http://}"
fi

# Function to generate .env file from runtime environment variables
generate_env_file() {
    echo "[OpenAlgo] Generating .env file from environment variables..."
    
    if ! touch "$ENV_FILE" 2>/dev/null; then
        echo "[OpenAlgo] Cannot write to /app/.env, using /tmp/.env"
        ENV_FILE="/tmp/.env"
    fi

    cat > "$ENV_FILE" << EOF
# OpenAlgo Environment Configuration File
# Auto-generated by Docker entrypoint
ENV_CONFIG_VERSION = '${ENV_CONFIG_VERSION:-1.0.4}'

# Broker Configuration
BROKER_API_KEY = '${BROKER_API_KEY:-}'
BROKER_API_SECRET = '${BROKER_API_SECRET:-}'

# Market Data Configuration (XTS Brokers only)
BROKER_API_KEY_MARKET = '${BROKER_API_KEY_MARKET:-}'
BROKER_API_SECRET_MARKET = '${BROKER_API_SECRET_MARKET:-}'

# Redirect URL
REDIRECT_URL = '${REDIRECT_URL:-}'

# Valid Brokers Configuration
VALID_BROKERS = '${VALID_BROKERS:-fivepaisa,fivepaisaxts,aliceblue,angel,arrow,compositedge,definedge,deltaexchange,dhan,dhan_sandbox,firstock,flattrade,fyers,groww,hdfcsky,ibulls,iifl,iiflcapital,indmoney,jainamxts,kotak,motilal,mstock,nubra,paytm,pocketful,rmoney,samco,shoonya,tradejini,tradesmart,upstox,wisdom,zebu,zerodha}'

# Security Configuration
APP_KEY = '${APP_KEY:-}'
API_KEY_PEPPER = '${API_KEY_PEPPER:-}'

# Database Configuration
DATABASE_URL = '${DATABASE_URL:-sqlite:///db/openalgo.db}'
LATENCY_DATABASE_URL = '${LATENCY_DATABASE_URL:-sqlite:///db/latency.db}'
LOGS_DATABASE_URL = '${LOGS_DATABASE_URL:-sqlite:///db/logs.db}'
SANDBOX_DATABASE_URL = '${SANDBOX_DATABASE_URL:-sqlite:///db/sandbox.db}'

# Ngrok - Disabled for cloud deployment
NGROK_ALLOW = '${NGROK_ALLOW:-FALSE}'

# Host Server
HOST_SERVER = '${HOST_SERVER:-}'

# Flask Configuration
FLASK_HOST_IP = '0.0.0.0'
FLASK_PORT = '${APP_PORT}'
FLASK_DEBUG = '${FLASK_DEBUG:-0}'
FLASK_ENV = '${FLASK_ENV:-production}'

# WebSocket Configuration
WEBSOCKET_HOST = '0.0.0.0'
WEBSOCKET_PORT = '${WEBSOCKET_PORT:-8765}'
EOF

    if [ -n "$WEBSOCKET_URL" ]; then
        echo "WEBSOCKET_URL = '${WEBSOCKET_URL}'" >> "$ENV_FILE"
    elif [ -n "$HOST_DOMAIN" ]; then
        echo "WEBSOCKET_URL = 'wss://${HOST_DOMAIN}/ws'" >> "$ENV_FILE"
    else
        echo "WEBSOCKET_URL = ''" >> "$ENV_FILE"
    fi

    cat >> "$ENV_FILE" << EOF

# ZeroMQ Configuration (Internal bus - loopback only)
ZMQ_HOST = '127.0.0.1'
ZMQ_PORT = '${ZMQ_PORT:-5555}'

# Logging Configuration
LOG_TO_FILE = '${LOG_TO_FILE:-True}'
LOG_LEVEL = '${LOG_LEVEL:-INFO}'
LOG_DIR = '${LOG_DIR:-log}'
LOG_FORMAT = '${LOG_FORMAT:-[%(asctime)s] %(levelname)s in %(module)s: %(message)s}'
LOG_RETENTION = '${LOG_RETENTION:-14}'
LOG_COLORS = '${LOG_COLORS:-True}'
FORCE_COLOR = '${FORCE_COLOR:-1}'

# Rate Limit Settings
LOGIN_RATE_LIMIT_MIN = '${LOGIN_RATE_LIMIT_MIN:-5 per minute}'
LOGIN_RATE_LIMIT_HOUR = '${LOGIN_RATE_LIMIT_HOUR:-25 per hour}'
RESET_RATE_LIMIT = '${RESET_RATE_LIMIT:-15 per hour}'
API_RATE_LIMIT = '${API_RATE_LIMIT:-50 per second}'
ORDER_RATE_LIMIT = '${ORDER_RATE_LIMIT:-10 per second}'
SMART_ORDER_RATE_LIMIT = '${SMART_ORDER_RATE_LIMIT:-10 per second}'
WEBHOOK_RATE_LIMIT = '${WEBHOOK_RATE_LIMIT:-100 per minute}'
STRATEGY_RATE_LIMIT = '${STRATEGY_RATE_LIMIT:-200 per minute}'

# API Configuration
SESSION_EXPIRY_TIME = '${SESSION_EXPIRY_TIME:-03:00}'

# CORS Configuration
CORS_ENABLED = '${CORS_ENABLED:-TRUE}'
CORS_ALLOWED_ORIGINS = '${CORS_ALLOWED_ORIGINS:-${HOST_SERVER}}'
CORS_ALLOWED_METHODS = '${CORS_ALLOWED_METHODS:-GET,POST,DELETE,PUT,PATCH}'
CORS_ALLOWED_HEADERS = '${CORS_ALLOWED_HEADERS:-Content-Type,Authorization,X-Requested-With}'
CORS_EXPOSED_HEADERS = '${CORS_EXPOSED_HEADERS:-}'
CORS_ALLOW_CREDENTIALS = '${CORS_ALLOW_CREDENTIALS:-FALSE}'
CORS_MAX_AGE = '${CORS_MAX_AGE:-86400}'

# CSP Configuration
CSP_ENABLED = '${CSP_ENABLED:-TRUE}'
CSP_REPORT_ONLY = '${CSP_REPORT_ONLY:-FALSE}'
CSP_DEFAULT_SRC = "'self'"
CSP_SCRIPT_SRC = "'self' 'unsafe-inline' https://cdn.socket.io https://static.cloudflareinsights.com"
CSP_STYLE_SRC = "'self' 'unsafe-inline'"
CSP_IMG_SRC = "'self' data:"
EOF

    if [ -n "$HOST_DOMAIN" ]; then
        echo "CSP_CONNECT_SRC = \"'self' wss://${HOST_DOMAIN} wss: ws: https://cdn.socket.io\"" >> "$ENV_FILE"
    else
        echo "CSP_CONNECT_SRC = \"'self' wss: ws: https://cdn.socket.io\"" >> "$ENV_FILE"
    fi

    cat >> "$ENV_FILE" << EOF
CSP_FONT_SRC = "'self'"
CSP_OBJECT_SRC = "'none'"
CSP_MEDIA_SRC = "'self' data: https://*.amazonaws.com https://*.cloudfront.net"
CSP_FRAME_SRC = "'self'"
CSP_FORM_ACTION = "'self'"
CSP_FRAME_ANCESTORS = "'self'"
CSP_BASE_URI = "'self'"
CSP_UPGRADE_INSECURE_REQUESTS = 'TRUE'
CSP_REPORT_URI = ''

# CSRF Configuration
CSRF_ENABLED = 'TRUE'
CSRF_TIME_LIMIT = ''

# Cookie Configuration
SESSION_COOKIE_NAME = 'session'
CSRF_COOKIE_NAME = 'csrf_token'
EOF

    echo "[OpenAlgo] .env file generated successfully at $ENV_FILE"

    if [ "$ENV_FILE" = "/tmp/.env" ]; then
        ln -sf /tmp/.env /app/.env 2>/dev/null || cp /tmp/.env /app/.env 2>/dev/null || true
        echo "[OpenAlgo] Linked .env to /app/.env"
    fi
}

# Check if .env exists and has content, otherwise auto-generate
if [ -f "$ENV_FILE" ] && [ -r "$ENV_FILE" ] && [ -s "$ENV_FILE" ]; then
    echo "[OpenAlgo] Using existing .env file"
else
    if [ -n "$HOST_SERVER" ]; then
        generate_env_file
    else
        echo "============================================"
        echo "Error: No .env file and HOST_SERVER not set"
        echo ""
        echo "For cloud deployment, set these environment variables:"
        echo "  - HOST_SERVER (e.g., https://your-app.example.com)"
        echo "  - REDIRECT_URL"
        echo "  - BROKER_API_KEY"
        echo "  - BROKER_API_SECRET"
        echo "  - APP_KEY (python -c \"import secrets; print(secrets.token_hex(32))\")"
        echo "  - API_KEY_PEPPER (generate another hex token)"
        echo "============================================"
        exit 1
    fi
fi

# Ensure required directories exist
for dir in db log log/strategies strategies strategies/scripts keys tmp tmp/numba_cache tmp/matplotlib; do
    mkdir -p "$dir" 2>/dev/null || true
done

if [ -w "." ]; then
    chmod -R 755 db log strategies tmp 2>/dev/null || true
    chmod 700 keys 2>/dev/null || true
fi

cd /app

# Pre-flight check for compromised default keys
PLACEHOLDER_APP_KEY="OPENALGO_PLACEHOLDER_APP_KEY_REGENERATE_BEFORE_USE"
PLACEHOLDER_PEPPER="OPENALGO_PLACEHOLDER_API_KEY_PEPPER_REGENERATE_BEFORE_USE"
LEAKED_APP_KEY="3daa0403ce2501ee7432b75bf100048e3cf510d63d2754f952729a991d8e2417"
LEAKED_PEPPER="a25d94718479b170c16278e321ea6c989358bf499a658fd20c90033cef8ce772"

if [ -f "/app/.env" ]; then
    CURRENT_APP_KEY=$(grep '^APP_KEY' /app/.env 2>/dev/null | sed -E "s/.*=\s*'([^']*)'.*/\1/" | head -n1)
    CURRENT_PEPPER=$(grep '^API_KEY_PEPPER' /app/.env 2>/dev/null | sed -E "s/.*=\s*'([^']*)'.*/\1/" | head -n1)

    KEY_COMPROMISED=0
    case "$CURRENT_APP_KEY" in
        "$PLACEHOLDER_APP_KEY"|"$LEAKED_APP_KEY") KEY_COMPROMISED=1 ;;
    esac
    case "$CURRENT_PEPPER" in
        "$PLACEHOLDER_PEPPER"|"$LEAKED_PEPPER") KEY_COMPROMISED=1 ;;
    esac

    if [ "$KEY_COMPROMISED" -eq 1 ]; then
        if ! touch /app/.env.permcheck 2>/dev/null; then
            cat <<'PREFLIGHT_ERR' >&2

============================================================
[OpenAlgo] STARTUP BLOCKED — compromised APP_KEY detected
============================================================
Your .env contains default or leaked APP_KEY / API_KEY_PEPPER.
Please generate new secret keys in your .env file or environment settings.
============================================================
PREFLIGHT_ERR
            exit 1
        fi
        rm -f /app/.env.permcheck
    fi
fi

# Run database migrations if available
if [ -f "/app/upgrade/migrate_all.py" ]; then
    echo "[OpenAlgo] Running database migrations..."
    /app/.venv/bin/python /app/upgrade/migrate_all.py || echo "[OpenAlgo] Migration completed (some steps skipped)"
else
    echo "[OpenAlgo] No migration script found, skipping."
fi

# Start WebSocket proxy server
echo "[OpenAlgo] Starting WebSocket proxy server on port ${WEBSOCKET_PORT:-8765}..."
/app/.venv/bin/python -m websocket_proxy.server &
WEBSOCKET_PID=$!
echo "[OpenAlgo] WebSocket proxy server started with PID $WEBSOCKET_PID"

# Signal handler for graceful shutdown
cleanup() {
    echo "[OpenAlgo] Shutting down..."
    if [ -n "$WEBSOCKET_PID" ]; then
        kill $WEBSOCKET_PID 2>/dev/null || true
    fi
    exit 0
}
trap cleanup SIGTERM SIGINT

# Create gunicorn worker temp directory inside container
mkdir -p /tmp/gunicorn_workers

# Start Gunicorn server
echo "[OpenAlgo] Starting web application on port ${APP_PORT} with eventlet..."
exec /app/.venv/bin/gunicorn \
    --worker-class eventlet \
    --workers 1 \
    --bind 0.0.0.0:${APP_PORT} \
    --timeout 300 \
    --graceful-timeout 30 \
    --worker-tmp-dir /tmp/gunicorn_workers \
    --no-control-socket \
    --log-level warning \
    app:app
